name: Python(Conda)

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Add conda to system path
      # $CONDA is an environment variable pointing to the root of the miniconda directory
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -q pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
        conda install -q pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
